version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: zayanori_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-zayanori_ecom}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: zayanori_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-zayanori_ecom}
      - SECRET_KEY=${SECRET_KEY:-your_very_secret_key_here}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - UPLOAD_DIR=/backend/uploads
      - FRONTEND_URL=http://localhost:4200
    volumes:
      - ./uploads:/backend/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: zayanori_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@syscomatic.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
